eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8081/eureka/
server:
    port: 8184
spring:
    application:
        name: service-zuul
zuul:
    routes:
        api-b:
            path: /api-b/**
            serviceId: consumer-feign